import type { Metadata } from "next";
import "./styles/globals.css";
import Section from "./layouts/Section/Section";
import Main from "./layouts/Main/Main";
import Header from "./layouts/Header/Header";
import StyledComponentsRegistry from "@/app/lib/registry";

export const metadata: Metadata = {
  title: "Event planner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <Header />
          <Main>
            <Section>{children}</Section>
          </Main>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
